trigger:
  - master

pool:
  vmImage: "ubuntu-latest"

variables:
  buildConfiguration: "Release"

  # Azure resources
  azureServiceConnection: "Azure subscription 1(1)(26a2e343-0fd6-4f21-b3d7-d4dca09b50c2)"
  appServiceName: "lms-api"

steps:
  # ============================================================
  # 1. Install .NET 10 SDK
  # ============================================================

  - task: UseDotNet@2
    displayName: "Use .NET 10 SDK"
    inputs:
      packageType: "sdk"
      version: "10.x"

  # ============================================================
  # 2. Display .NET Information
  # ============================================================

  - script: |
      dotnet --info
    displayName: "Display .NET Information"

  # ============================================================
  # 3. Restore NuGet Packages
  # ============================================================

  - task: DotNetCoreCLI@2
    displayName: "Restore Dependencies"
    inputs:
      command: "restore"
      projects: "**/*.csproj"

  # ============================================================
  # 4. Build Solution
  # ============================================================

  - task: DotNetCoreCLI@2
    displayName: "Build Solution"
    inputs:
      command: "build"
      projects: "**/*.csproj"
      arguments: "--configuration $(buildConfiguration) --no-restore"

  # ============================================================
  # 5. Run Unit Tests
  # ============================================================

  # Uncomment if you have test projects

  # - task: DotNetCoreCLI@2
  #   displayName: 'Run Unit Tests'
  #   inputs:
  #     command: 'test'
  #     projects: '**/*Tests/*.csproj'
  #     arguments: '--configuration $(buildConfiguration) --no-build'
  #     publishTestResults: true

  - task: DotNetCoreCLI@2
    displayName: "Publish API"
    inputs:
      command: "publish"
      publishWebProjects: true
      arguments: "--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)"
      zipAfterPublish: true

  # ============================================================
  # 12. Publish Build Artifacts
  # ============================================================

  - task: PublishBuildArtifacts@1
    displayName: "Publish Artifacts"
    inputs:
      PathtoPublish: "$(Build.ArtifactStagingDirectory)"
      ArtifactName: "drop"
      publishLocation: "Container"

  # ============================================================
  # 13. Deploy API to Azure App Service
  # ============================================================

  - task: AzureWebApp@1
    displayName: "Deploy to Azure App Service"
    inputs:
      azureSubscription: "$(azureServiceConnection)"
      appType: "webApp"
      appName: "$(appServiceName)"
      package: "$(Build.ArtifactStagingDirectory)/app/*.zip"
      deploymentMethod: "auto"
